### ISSUE TITLE
update script error while running update on Brother MFC9332CDW

### ISSUE THREAD

**Issue by typoworx-de** [CauldronDevelopmentLLC/oh-brother#24]
This is the call and trace of program. Printer somehow seemed to initialize update anyway?!
```
./oh-brother.py 192.168.160.240
You may need to check the following in the printer's configuration:
  - SNMP service is enabled (for fetching model and versions)
  - FTP service is enabled (for uploading firmware)
  - an administrator password is set (for connecting to FTP)
Press Ctrl-C to exit or Enter to continue...
Getting SNMP data from printer at 192.168.160.240...
done

      serial = E74554L7J531663
       model = MFC-9332CDW
        spec = 0403
   firmwares
            category = MAIN, version = L1704111435:8668
            category = SUB1, version = 1.04
            category = SUB2, version = P1707051300


Updating MAIN version L1704111435:8668
Looking up printer firmware info at vendor server...
done
Downloading firmware file LZ5413_P.djf from vendor server...
............................................................................................................done
About to upload the firmware to printer.
This is a dangerous action since it is potentially destructive.
Thus please double-check / review to ensure that:
- firmware file version is compatible with your hardware
- network connection is reliable (prefer wired connection to WLAN)
- power is reliable
Press Ctrl-C to prevent upgrade or Enter to continue... 

Enter printer admin password: 
Now uploading firmware to printer (DO NOT REMOVE POWER!)...
done

Wait for printer to finish updating and reboot before continuing.
Press Enter to continue...

Updating SUB1 version 1.04
Looking up printer firmware info at vendor server...
done
Downloading firmware file LZ5414_E.djf from vendor server...
......................................................................done
About to upload the firmware to printer.
This is a dangerous action since it is potentially destructive.
Thus please double-check / review to ensure that:
- firmware file version is compatible with your hardware
- network connection is reliable (prefer wired connection to WLAN)
- power is reliable
Press Ctrl-C to prevent upgrade or Enter to continue...
Now uploading firmware to printer (DO NOT REMOVE POWER!)...
Traceback (most recent call last):
  File "./oh-brother.py", line 298, in <module>
    update_firmware(entry['cat'], entry['version'])
  File "./oh-brother.py", line 285, in update_firmware
    ftp = FTP(args.ip, user = args.password) # Yes send password as user
  File "/usr/lib/python2.7/ftplib.py", line 122, in __init__
    self.login(user, passwd, acct)
  File "/usr/lib/python2.7/ftplib.py", line 392, in login
    resp = self.sendcmd('USER ' + user)
  File "/usr/lib/python2.7/ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 215, in getresp
    resp = self.getmultiline()
  File "/usr/lib/python2.7/ftplib.py", line 201, in getmultiline
    line = self.getline()
  File "/usr/lib/python2.7/ftplib.py", line 191, in getline
    if not line: raise EOFError
EOFError
```

**Comment by typoworx-de** [comment]
Firmware update failed. Firmware shown in menu is 1.04 - same version reported above when the script initially started. I think there's something stuck in the firmware-update?

**Comment by typoworx-de** [comment]
Seems to work fine after reinstalling python in recent version, reinstalling pip (web-installer latest version) and reinstalling pip requirements.

**Comment by mcmaxl** [comment]
Hi @typoworx-de I am currently trying to install the ifax firmware, however, I'm getting a snmp timeout error after starting the script with the printers ip address. Since I have the same printer as you (MFC9332CDW) I was wondering: how did you set the admin password? I have indeed changed the login password for the printer website but cannot find an option for an admin password.
