### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by rowdy15** [CauldronDevelopmentLLC/oh-brother#38]
I am getting the following error when I run the code.

`You may need to check the following in the printer's configuration:
  - SNMP service is enabled (for fetching model and versions)
  - FTP service is enabled (for uploading firmware)
  - an administrator password is set (for connecting to FTP)
Press Ctrl-C to exit or Enter to continue...
Getting SNMP data from printer at 192.168.1.46...
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 45, in runDispatcher
    loop(timeout or self.getTimerResolution(),
  File "/usr/lib/python3.11/asyncore.py", line 212, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.11/asyncore.py", line 193, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python3.11/asyncore.py", line 128, in readwrite
    obj.handle_error()
  File "/usr/lib/python3.11/asyncore.py", line 113, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python3.11/asyncore.py", line 425, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/base.py", line 84, in _cbFun
    self.__recvCallables[recvId](
  File "/usr/lib/python3.11/site-packages/pysnmp/entity/engine.py", line 151, in __receiveMessageCbFun
    self.msgAndPduDsp.receiveMessage(
  File "/usr/lib/python3.11/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pysnmp/proto/api/verdec.py", line 15, in decodeMessageVersion
    seq, wholeMsg = decoder.decode(
                    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 1918, in __iter__
    for asn1Object in self._singleItemDecoder(
  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decodeMessageVersion.<locals>.<lambda>() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/Downloads/oh-brother-master/oh-brother-master/./oh-brother.py", line 95, in <module>
    error, status, index, table = cg.nextCmd(
                                  ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 214, in nextCmd
    for (errorIndication,
  File "/usr/lib/python3.11/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 362, in nextCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 45, in runDispatcher
    loop(timeout or self.getTimerResolution(),
;  File "/usr/lib/python3.11/asyncore.py", line 212, in loop
    poll_fun(timeout, map)
;  File "/usr/lib/python3.11/asyncore.py", line 193, in poll2
    readwrite(obj, flags)
;  File "/usr/lib/python3.11/asyncore.py", line 128, in readwrite
    obj.handle_error()
;  File "/usr/lib/python3.11/asyncore.py", line 113, in readwrite
    obj.handle_read_event()
;  File "/usr/lib/python3.11/asyncore.py", line 425, in handle_read_event
    self.handle_read()
;  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "/usr/lib/python3.11/site-packages/pysnmp/carrier/base.py", line 84, in _cbFun
    self.__recvCallables[recvId](
;  File "/usr/lib/python3.11/site-packages/pysnmp/entity/engine.py", line 151, in __receiveMessageCbFun
    self.msgAndPduDsp.receiveMessage(
;  File "/usr/lib/python3.11/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
;  File "/usr/lib/python3.11/site-packages/pysnmp/proto/api/verdec.py", line 15, in decodeMessageVersion
    seq, wholeMsg = decoder.decode(
                    ^^^^^^^^^^^^^^^
;  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
;  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 1918, in __iter__
    for asn1Object in self._singleItemDecoder(
;  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
;  File "/usr/lib/python3.11/site-packages/pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
;TypeError: decodeMessageVersion.<locals>.<lambda>() takes 3 positional arguments but 4 were given
caused by <class 'TypeError'>: decodeMessageVersion.<locals>.<lambda>() takes 3 positional arguments but 4 were given
[sam@LinuxDesktopPC oh-brother-master]$ yay python3-pysnmp4
`

what could be the problem?

**Comment by thechickenmoo** [comment]
Same issue with an MFC-8890DW. It seems to be having trouble decoding the response from SNMP?
