### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by mcmaxl** [CauldronDevelopmentLLC/oh-brother#39]
Hi all,

I installed pysnmp using pip3 on macOS Sonoma 14.4.1 (Python 3.12.3) and I am getting the following error while running the script from my user directory:
```
Maxbook:~ maxl$ /Users/oh-brother.py --category IFAX 192.168.178.125
Traceback (most recent call last):
  File "/Users/oh-brother.py", line 17, in <module>
    from pysnmp.entity.rfc3413.oneliner import cmdgen
  File "/usr/local/lib/python3.12/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 10, in <module>
    from pysnmp.hlapi.asyncore import *
  File "/usr/local/lib/python3.12/site-packages/pysnmp/hlapi/__init__.py", line 9, in <module>
    from pysnmp.smi.rfc1902 import *
  File "/usr/local/lib/python3.12/site-packages/pysnmp/smi/rfc1902.py", line 10, in <module>
    from pysnmp.smi.builder import ZipMibSource
  File "/usr/local/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 9, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

any ideas whats goging on?

Help greatly appreciated as I cannot install the IFAX firmware on my MFC9332CDW after installing the most recent main firmware update.

**Comment by mcmaxl** [comment]
> Hi all,
> 
> 
> 
> I installed pysnmp using pip3 on macOS Sonoma 14.4.1 (Python 3.12.3) and I am getting the following error while running the script from my user directory:
> 
> ```
> 
> Maxbook:~ maxl$ /Users/oh-brother.py --category IFAX 192.168.178.125
> 
> Traceback (most recent call last):
> 
>   File "/Users/oh-brother.py", line 17, in <module>
> 
>     from pysnmp.entity.rfc3413.oneliner import cmdgen
> 
>   File "/usr/local/lib/python3.12/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 10, in <module>
> 
>     from pysnmp.hlapi.asyncore import *
> 
>   File "/usr/local/lib/python3.12/site-packages/pysnmp/hlapi/__init__.py", line 9, in <module>
> 
>     from pysnmp.smi.rfc1902 import *
> 
>   File "/usr/local/lib/python3.12/site-packages/pysnmp/smi/rfc1902.py", line 10, in <module>
> 
>     from pysnmp.smi.builder import ZipMibSource
> 
>   File "/usr/local/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 9, in <module>
> 
>     import imp
> 
> ModuleNotFoundError: No module named 'imp'
> 
> ```
> 
> 
> 
> any ideas whats goging on?
> 
> 
> 
> Help greatly appreciated as I cannot install the IFAX firmware on my MFC9332CDW after installing the most recent main firmware update.

Update: it's an issue with python 3.12 - works well in 3.11
